server:
  port: 0

spring:
  application:
    name: main-service
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org.hibernate: ERROR
    org.hibernate.SQL: OFF

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/