CREATE TABLE IF NOT EXISTS categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat DECIMAL(9,6) NOT NULL,
    lon DECIMAL(9,6) NOT NULL
);

CREATE TABLE IF NOT EXISTS events(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    annotation TEXT,
    description TEXT,
    initiator_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    confirmed_requests BIGINT NOT NULL DEFAULT 0,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    paid BOOLEAN DEFAULT false,
    participant_limit BIGINT NOT NULL DEFAULT 0,
    request_moderation BOOLEAN DEFAULT true,
    state TEXT NOT NULL,
    views BIGINT DEFAULT 0,

    CONSTRAINT fk_events_categories
        FOREIGN KEY(category_id) REFERENCES categories(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_events_users
        FOREIGN KEY(initiator_id) REFERENCES users(id),
    CONSTRAINT fk_events_locations
        FOREIGN KEY(location_id) REFERENCES locations(id)
);