-- Создание схемы
CREATE SCHEMA IF NOT EXISTS ewm_users;

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS ewm_users.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);