server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service #http://localhost:

          predicates:
            - Path=/admin/users/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/