-- Создание схемы
CREATE SCHEMA IF NOT EXISTS ewm_events;

-- Таблица категорий
CREATE TABLE IF NOT EXISTS ewm_events.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- Таблица локаций
CREATE TABLE IF NOT EXISTS ewm_events.locations (
    id BIGSERIAL PRIMARY KEY,
    lat DECIMAL(9,6) NOT NULL,
    lon DECIMAL(9,6) NOT NULL
);

-- Таблица событий
CREATE TABLE IF NOT EXISTS ewm_events.events (
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    annotation TEXT,
    description TEXT,
    initiator_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    paid BOOLEAN DEFAULT FALSE,
    participant_limit BIGINT NOT NULL DEFAULT 0,
    request_moderation BOOLEAN DEFAULT TRUE,
    state TEXT NOT NULL,

    CONSTRAINT fk_events_categories
        FOREIGN KEY(category_id) REFERENCES ewm_events.categories(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_events_locations
        FOREIGN KEY(location_id) REFERENCES ewm_events.locations(id)
        ON DELETE RESTRICT
);

-- Таблица подборок
CREATE TABLE IF NOT EXISTS ewm_events.compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN DEFAULT FALSE,
    title TEXT NOT NULL UNIQUE
);

-- Связующая таблица подборок и событий
CREATE TABLE IF NOT EXISTS ewm_events.compilation_event (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT pk_compilation_event PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_event_compilation
        FOREIGN KEY(compilation_id) REFERENCES ewm_events.compilations(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_compilation_event_event
        FOREIGN KEY(event_id) REFERENCES ewm_events.events(id)
        ON DELETE CASCADE
);
